cache-dir = "auto"
log-file = "auto"
api-expire = 3600
checksum = "Always"
selected-instance = "dotminecraft"
get-optional-dependencies = false
ignored-mods = []
#Color = true

# enable downloading mods for upstream mod loaders
# for example downloading fabric mods when using a quilt client
# enabling this feature may result in unexpected mod behaviour
allow-upstream = false
