name: cxfreeze

on:
  push:
    branches:
      - main
      - dev

jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -U cxfreeze appdirs tomlkit requests pyyaml
      - run: python setup.py build
      - run: tar czfC dist/mcmodman_linux_x86_64.tar.gz dist .
      - uses: actions/upload-artifact@v4
        with:
          name: mcmodman_linux_x86_64
          path: dist/mcmodman_linux_x86_64.tar.gz


  macos:
    runs-on: macos-14
    env:
      MACOSX_DEPLOYMENT_TARGET: '11.0'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -U cxfreeze appdirs tomlkit requests pyyaml
      - run: python setup.py build
      - run: tar czfC dist/mcmodman_macos_aarch64.tar.gz dist .
      - uses: actions/upload-artifact@v4
        with:
          name: mcmodman_macos_aarch64
          path: dist/mcmodman_macos_aarch64.tar.gz

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -U cxfreeze appdirs tomlkit requests pyyaml
      - run: python setup.py build
      - run: Compress-Archive -Path dist/* -DestinationPath dist/mcmodman_windows_x86_64.zip
      - uses: actions/upload-artifact@v4
        with:
          name: mcmodman_windows_x86_64
          path: dist/mcmodman_windows_x86_64.zip
          