name: pyinstaller

on:
  push:
    branches:
      - main
      - dev

jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -U pyinstaller appdirs toml requests pyyaml
      - run: pyinstaller --onefile mcmodman.py indexing.py commons.py modrinth.py local.py instance.py cache.py --add-data=dataversion.json:dataversion.json --add-data=config-template.toml:config-template.toml
      - run: tar czfC dist/mcmodman_linux_x86_64.tar.gz dist mcmodman
      - uses: actions/upload-artifact@v4
        with:
          name: mcmodman_linux_x86_64
          path: dist/mcmodman_linux_x86_64.tar.gz


  macos:
    runs-on: macos-14
    env:
      MACOSX_DEPLOYMENT_TARGET: '11.0'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -U pyinstaller appdirs toml requests pyyaml
      - run: pyinstaller --onefile mcmodman.py indexing.py commons.py modrinth.py local.py instance.py cache.py --add-data=dataversion.json:dataversion.json --add-data=config-template.toml:config-template.toml
      - run: tar czfC dist/mcmodman_macos_aarch64.tar.gz dist mcmodman
      - uses: actions/upload-artifact@v4
        with:
          name: mcmodman_macos_aarch64
          path: dist/mcmodman_macos_aarch64.tar.gz

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -U pyinstaller appdirs toml requests pyyaml
      - run: pyinstaller --onefile mcmodman.py indexing.py commons.py modrinth.py local.py instance.py cache.py --add-data=dataversion.json:dataversion.json --add-data=config-template.toml:config-template.toml
      - run: Compress-Archive -Path dist/mcmodman.exe -DestinationPath dist/mcmodman_windows_x86_64.zip
      - uses: actions/upload-artifact@v4
        with:
          name: mcmodman_windows_x86_64
          path: dist/mcmodman_windows_x86_64.zip