name: Pylint

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint appdirs toml requests
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --fail-on 9.25 --disable=W0311 --disable=C0301
